# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83adf3ef43679863a61d9b093166b57235de72501b4481ffe26c3874c32d601705078d32f8db643ed3dec7f9d2cabca90afcbc8fef4b5785f1abfb8ac145cad6

test:
  secret_key_base: 87e648423637dba08e1ba464c3a22c43be3215590f3d5e9e57601de98e6a1f181fe66c718e4039507482a0a5f04c6673e4885a6515a9d23a633ad9e906706f9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
